server:
  port: 8082

external-client:
  stock-prices:
    domain: http://localhost:8081
    path: /stock/price/v1/enquiry
  properties:
    client-timeout: 30s
    max-retry:
      attempt: 3
      interval: 1s

memory-buffer-size: 16777216
